### ISSUE TITLE
ResponseError: bit offset is not an integer or out of range

### ISSUE THREAD

**Issue by muminoff** [Doist/bitmapist#12]
```python
>>> myid
10204510554222024
>>> mark_event('active', myid)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/sardor/.virtualenvs/tarjimonlar/local/lib/python2.7/site-packages/bitmapist/__init__.py", line 173, in mark_event
    client.execute() 
  File "/home/sardor/.virtualenvs/tarjimonlar/local/lib/python2.7/site-packages/redis/client.py", line 2578, in execute
    return execute(conn, stack, raise_on_error)
  File "/home/sardor/.virtualenvs/tarjimonlar/local/lib/python2.7/site-packages/redis/client.py", line 2492, in _execute_transaction
    self.raise_first_error(commands, response)
  File "/home/sardor/.virtualenvs/tarjimonlar/local/lib/python2.7/site-packages/redis/client.py", line 2526, in raise_first_error
    raise r
ResponseError: Command # 1 (SETBIT trackist_active_2015-3 10204510554222024 1) of pipeline caused error: bit offset is not an integer or out of range
>>> 
```

**Comment by muminoff** [comment]
I now got the point. From Redis documentation:

```
The offset argument is required to be greater than or equal to 0, and smaller than 232 (this limits bitmaps to 512MB).
```
